-- Earn Chat — conversion analytics storage
-- Run this in the Supabase SQL Editor before publishing earn_chat_advanced_v1.html.
-- This adds measurement only. It does not modify the existing profiles table or app design.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (char_length(event_name) between 1 and 80),
  user_id uuid null references auth.users(id) on delete set null,
  session_id text not null,
  page_id text null,
  source text not null default 'web',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);
create index if not exists analytics_events_event_name_idx
  on public.analytics_events (event_name, created_at desc);
create index if not exists analytics_events_user_id_idx
  on public.analytics_events (user_id, created_at desc);
create index if not exists analytics_events_session_id_idx
  on public.analytics_events (session_id, created_at desc);

alter table public.analytics_events enable row level security;

-- Visitors may insert anonymous events only when user_id is null.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'analytics_events'
      and policyname = 'anonymous visitors can insert analytics'
  ) then
    create policy "anonymous visitors can insert analytics"
      on public.analytics_events
      for insert
      to anon
      with check (user_id is null);
  end if;
end $$;

-- Logged-in users may insert events only for their own auth user id.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'analytics_events'
      and policyname = 'authenticated users can insert own analytics'
  ) then
    create policy "authenticated users can insert own analytics"
      on public.analytics_events
      for insert
      to authenticated
      with check (user_id is null or user_id = auth.uid());
  end if;
end $$;

-- No browser-side SELECT policy is added intentionally.
-- Review analytics in the Supabase dashboard or later through a secure admin endpoint.

-- Useful funnel query:
-- select event_name, count(*) as events, count(distinct session_id) as sessions
-- from public.analytics_events
-- where created_at >= now() - interval '7 days'
-- group by event_name
-- order by sessions desc;

-- Registration failure breakdown:
-- select metadata->>'stage' as stage,
--        metadata->>'code' as code,
--        count(*) as failures
-- from public.analytics_events
-- where event_name = 'registration_failed'
--   and created_at >= now() - interval '7 days'
-- group by 1, 2
-- order by failures desc;

-- Push diagnostic summary:
-- select event_name,
--        metadata->>'notification_permission' as permission,
--        metadata->>'matching_service_worker' as service_worker_found,
--        metadata->>'push_subscription_present' as subscription_found,
--        count(*) as events
-- from public.analytics_events
-- where event_name in ('propush_script_loaded','propush_script_error','push_permission_state','push_diagnostic')
--   and created_at >= now() - interval '7 days'
-- group by 1, 2, 3, 4
-- order by events desc;
